#ifndef BUS_ACCESS_GLOBAL_H
#define BUS_ACCESS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BUSACCESS_LIBRARY)
#  define BUSACCESSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define BUSACCESSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // BUS_ACCESS_GLOBAL_H
