


#ifndef KERNEL_HARDWARE_NAME
	#define KERNEL_HARDWARE_NAME "BUS-Controller 2.3"
#endif

#ifndef HARDWARE_VERSION
	#define HARDWARE_VERSION_MAJOR 2
	#define HARDWARE_VERSION_MINOR 3
	#define HARDWARE_VERSION HARDWARE_VERSION_MAJOR,HARDWARE_VERSION_MINOR
#endif

#ifndef KERNEL_VERSION
	#define KERNEL_VERSION_MAJOR 2
	#define KERNEL_VERSION_MINOR 6
#endif
